name: CI/CD for Spring PetClinic

on:
  push:
    branches:
      - main

      jobs:
        build:
      
          runs-on: ubuntu-latest
          strategy:
            matrix:
              java: [ '17' ]
      
          steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'
                cache: maven
            - name: execute permission to Maven
              run: chmod +x mvnw
            - name: Build with Maven Wrapper 
              run: ./mvnw -B package

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: echo $KUBE_CONFIG_DATA | base64 -d > kubeconfig

    - name: Deploy to Kubernetes
      run: kubectl apply -f kubernetes/deployment.yaml
