name: CI/CD for Spring PetClinic

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: |
        docker build -t spring-petclinic .
        docker tag spring-petclinic YOUR_DOCKER_REGISTRY_USERNAME/spring-petclinic:latest
        docker push YOUR_DOCKER_REGISTRY_USERNAME/spring-petclinic:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: echo $KUBE_CONFIG_DATA | base64 -d > kubeconfig

    - name: Deploy to Kubernetes
      run: kubectl apply -f kubernetes/deployment.yaml
